# docker-compose.jenkins.yml
services:
  jenkins:
    build:
      context: ./jenkins  # Utilise notre Dockerfile personnalisé
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock