# docker-compose.yml (Version avec l'indentation finale et correcte)

services:
  # --- Backend Spring Boot ---
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/PFE
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - MQTT_BRIDGE_URL=http://mqtt-bridge:5001/api/capteurs
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      mqtt-bridge:
        condition: service_started
    networks:
      - app-net

  # --- Frontend React + Nginx ---
  frontend:
    build:
      context: ./youssef
    restart: unless-stopped
    dns:
      - 8.8.8.8
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-net

  # --- Base de Données PostgreSQL ---
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=PFE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PFE"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  # --- Broker MQTT Mosquitto ---
  # CORRECTION : Ajout de 2 espaces ici
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-config:/mosquitto/config
    networks:
      - app-net
      
  # --- Pont MQTT vers API (Python Flask) ---
  # CORRECTION : Ajout de 2 espaces ici
  mqtt-bridge:
    build:
      context: ./pythone-mqtt
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - MQTT_BROKER=mosquitto
    command: ["python", "-u", "mqtt_server.py"]
    depends_on:
      - mosquitto
    networks:
      - app-net

  # --- Simulateur de Capteur (Python Publisher) ---
  # CORRECTION : Ajout de 2 espaces ici
  sensor-publisher:
    build:
      context: ./pythone-mqtt
    restart: unless-stopped
    environment:
      - MQTT_BROKER=mosquitto
    command: ["python", "-u", "sensor_publisher.py"]
    depends_on:
      - mosquitto
    networks:
      - app-net

# --- Volumes & Réseaux ---
volumes:
  postgres_data:

networks:
  app-net:
    driver: bridge