# /jenkins/Dockerfile

FROM jenkins/jenkins:lts
USER root

# Installation de Docker
RUN apt-get update && apt-get install -y lsb-release erreur nous rapproche de la solution.

Vous avez résolu le problème de chemin, et maintenant la construction de votre image Jenkins personnalisée curl sudo
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring. a commencé. Elle a échoué à la toute dernière étape, ce qui est très facile à corriger.

###asc https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg Diagnostic de l'Erreur

Le message est très clair :